### ISSUE TITLE
Import sermon distributor VDM package Error

### ISSUE THREAD

**Issue by pirosoft** [Llewellynvdm/Joomla-Sermon-Distributor#35]
When i try to Import sermon distributor VDM package give me a error:

Error
Data is corrupt!
This could be due to key error, or broken package!
Import error.

But the key it's correct, i check many times.

thanks

**Comment by Llewellynvdm** [comment]
I have just tested this, and it works perfectly, but only on JCB version 2.13.0 upwards, or if you have access to JCB pro v3.5.0 upwards. We changed the encryption algorithmic way from FOF in preparation as we are moving to Joomla 4 and so none on the new packages will work on any versions below 2.13.0 and 3.5.0

Let me know if your still having issues.

**Comment by pirosoft** [comment]
Thanks, i  update JCB and now works!

thankyou
